### ISSUE TITLE
Add option for stripping Powerpress in podcasts

### ISSUE THREAD

**Issue by mvbattista** [wdwnt/fastpass#18]
Add `stripped_content` and `media_url` to Podcast payload

Questions to be answered:
- Do this for GET of Single object or multiple? This matters in the code.
- Is sending the same data twice going against the idea of FastPass? 
- Do we add a parameter to switch the output?
- Will this break the app?

POC code:
```
soup = BeautifulSoup(podcast_obj['content'],"html.parser")

download_url = soup.find('a', class_= 'powerpress_link_d')['href']
for tag in soup.select('div.powerpress_player'):
  tag.decompose()
for tag in soup.select('p.powerpress_links'):
  tag.decompose()

print(soup)
```

**Comment by rorpage** [comment]
My opinions/thoughts:
* Both please
* "same data twice" as in the unparsed description and then basically the same thing as the `stripped_content`?
* I don't think we need a parameter because...
* having two new properties would allow the apps to look for the same data and over time move over to start using the new properties

I also don't think this goes against what FP is meant to do as, in my opinion, FP was made to help simplify parsing, feeding to apps, using the data we have available. Basically it's payload manipulation and simplification with caching to make things super fast.

**Comment by mvbattista** [comment]
I'm looking at it as being a big HTML of the podcast post and it being sent twice, once in the `content` and again in the `stripped_content`, just without the PowerPress. Sending the same thing twice doesn't simplify parsing; it just makes it redundant and increases the payload of what we're sending of a factor that could be great.

Adding the property is something new calls can make and pass in. When we want to retire that functionality, it's just a matter of changing the default on the property.

**Comment by mvbattista** [comment]
We have a precedence for this with #11 where we simply add a flag.
